@args --debugger --no-ignore-try

we should enter a debug repl through tryEval
  nix-repl> (builtins.tryEval ((x: throw "foo") 1)).success
  error: foo

  This exception occurred in a 'tryEval' call. Use --ignore-try to skip these.

no segfault either
  nix-repl> :quit
  error: foo
